### ISSUE TITLE
vim mode

### ISSUE THREAD

**Issue by with-heart** [cerebral/webpackbin#11]
I see a few minimal references to vim in the source. Is there any work that needs done to make that a reality for webpackbin?

**Comment by christianalfoni** [comment]
@lionize Not that much really! I have never used it myself. Would it be something you consistently want to be ON? Like it could be under your profile settings, or is it something you turn on and off? I should be able to get it in quite quickly :)

**Comment by with-heart** [comment]
@christianalfoni Thanks for the quick reply!

It'd be something that's consistently enabled . Once I turn it on in something, it never goes off, and I'd say it's the same for most vim people. Profile settings sounds like the perfect place for it.

**Comment by christianalfoni** [comment]
@lionize Cool, let me look into it, should have it up there in a couple of days :)

**Comment by with-heart** [comment]
Awesome. Sounds great!

**Comment by christianalfoni** [comment]
Its out :-)

**Comment by with-heart** [comment]
@christianalfoni Awesome! Thank you!
