### ISSUE TITLE
Is it possible to somehow restore bins which were hosted on heroku?

### ISSUE THREAD

**Issue by istarkov** [cerebral/webpackbin#12]
Hi, is it possible to restore bins I created as a help for google-map-react
All the links here
https://github.com/istarkov/google-map-react/blob/master/DOC.md
Or I need to write them again?

**Comment by christianalfoni** [comment]
@istarkov Hi man... sorry to say that I took down the services for old webpackbin a few days ago. Webpackbin 2 was a fresh take on the whole service and it would require a lot of time on my part to make the old compatible with the new... time I just do not have :-(

So for about a month the old service ran and you would get a message on the new service when hitting an invalid url and you were moved to old service. But that is not possible anymore.

Sorry about that, but yeah, webpackbin has been a one man show this far, so just limited resources on making it best possible experience :-) So please add a new bin
