### ISSUE TITLE
New Boilerplates

### ISSUE THREAD

**Issue by with-heart** [cerebral/webpackbin#13]
Do you have a process for submitting new boilerplates to be listed on the site? I'd like to create one similar to `styled-components` for [glamorous](https://github.com/paypal/glamorous).

**Comment by christianalfoni** [comment]
@lionize That would be super awesome, just send me the link when you are done :-)

**Comment by with-heart** [comment]
@christianalfoni I threw together [https://www.webpackbin.com/bins/-KiLFxe-ey3VzezvgwFb](https://www.webpackbin.com/bins/-KiLFxe-ey3VzezvgwFb). I think it covers the basics pretty well.

**Comment by christianalfoni** [comment]
Sorry for being late, it is added now :)
