### ISSUE TITLE
where did my webpack bin go?

### ISSUE THREAD

**Issue by faceyspacey** [cerebral/webpackbin#18]
Here's the link: 

https://www.webpackbin.com/VyEINYf5z

It's now gone. Is there any way to recover it?

**Comment by christianalfoni** [comment]
@faceyspacey The old webpackbin was running for a little over a month, then it was shut down. It cost me over 100$ a month to run it... so just limited resources giving a "not ideal" user experience. Sorry about that :(

**Comment by faceyspacey** [comment]
...thank god i backed it up locally just in case. ...i'm excited to use webpackbin again with all the new features. keep up the great work!
