### ISSUE TITLE
base64 error with RxDB

### ISSUE THREAD

**Issue by natew** [cerebral/webpackbin#26]
Found another weird one!

https://www.webpackbin.com/bins/-KjnpS0w30PvOAe7y1Ja

Getting:

![image](https://cloud.githubusercontent.com/assets/12100/25917341/86abdce2-357c-11e7-8fa7-2f232bae0802.png)

**Comment by natew** [comment]
Managed to get it working with:

https://www.webpackbin.com/bins/-KjnqhD4klalpDbduZR-

**Comment by christianalfoni** [comment]
@natew Actually I got a couple of beers in me today and fixed the issue, also with "slate". Will be deployed during the day, and cache will be cleared to allow failed bin to rebundle the correct version :)

**Comment by christianalfoni** [comment]
Okay, deployed new version, you can try again now :)
