### ISSUE TITLE
Add boilerplates for JSS

### ISSUE THREAD

**Issue by typical000** [cerebral/webpackbin#32]
Can't find any way to submit new boilerplates.
@christianalfoni can you add some [JSS](http://cssinjs.org) boilerplates?
Here they are:

JSS:
https://www.webpackbin.com/bins/-KlrNqkpZZmKIz0eYwIk

React-JSS:
https://www.webpackbin.com/bins/-Klr_9GCg7ubIU3D9KFP

Styled-JSS:
https://www.webpackbin.com/bins/-KlrbQuwAZSK5eSzpCSy

**Comment by typical000** [comment]
Hello, any activity here?
Found that JSS is already added as boilerplate. Thanks! What about react-jss, styled-jss?

**Comment by christianalfoni** [comment]
Hi man :) 

Right in between me adding we had an issue with the CDN, so got interrupted. Added now :)

**Comment by typical000** [comment]
Cool! Thanks! So, we can close this issue
