### ISSUE TITLE
Error on bin - but runs ok after downloading

### ISSUE THREAD

**Issue by FDiskas** [cerebral/webpackbin#33]
Here is a bin: https://www.webpackbin.com/bins/-Km0PFss7TpzU6HR4xBI
shows an error, but if you download it and run locally then there is no errors.

**Comment by christianalfoni** [comment]
Hi there @FDiskas , for some reason axios has this in their package.json:

```
  "browser": {
    "./lib/adapters/http.js": "./lib/adapters/xhr.js"
  },
```

We value `browser` entries more than `main` entries... I have no idea why axios does this though, does not make any sense to make them different.

I have to evaluate a bit here, will notify you :)

**Comment by FDiskas** [comment]
The idea of this setting in package.json is explaned here https://github.com/mzabriskie/axios/issues/456

**Comment by christianalfoni** [comment]
@FDiskas I just did some research and was not aware of this `browser` alias listing. It has currently been handled as entry points, which is of course wrong. Will just ignore this for now as Webpack will include both versions when evaluating this code:

```js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

Though of course choose the correct one in runtime.

**Comment by FDiskas** [comment]
@christianalfoni thanks for the research - webpackbin now works :closed_umbrella:
