### ISSUE TITLE
Impossible to recover after: 413 Payload Too Large

### ISSUE THREAD

**Issue by ekulabuhov** [cerebral/webpackbin#44]
After trying to upload 97KB json file I got this error.

Deleting file, refreshing the browser and even opening a new tab - doesn't help.

Seems like the files are saved/retrieved using firebase first. Hitting cmd+S POSTs them to sandbox.webpackbin.com where the error is triggered. 

Here's example bin: https://www.webpackbin.com/bins/-KrqKsZP47q9olzHb9hN

**Comment by christianalfoni** [comment]
@ekulabuhov Hi there! Yeah, on every save it posts all the files in the sandbox. It is just too much. I would suggest using a JSON mocking API instead. For example: https://jsonplaceholder.typicode.com/
