### ISSUE TITLE
Can not initialize state directly as a class property without forcing no linting - React

### ISSUE THREAD

**Issue by dancomanlive** [cerebral/webpackbin#47]
When trying this example in webpackbin, without Force no linting option enabled, I get "Parsing error: Unexpected token =" I would very much like to be able to initialize state directly as a class property and use the linter at the same time. Thanks!

To initialize state in React component we used to do this in the constructor.

// BEFORE
```
import React, { Component } from "react";

class Counter extends Component {
  constructor(props) {
    super(props);

    this.state = { counter: 0 };
  }

  ...
}
```

Now we can initialize state directly as a class property.
// AFTER
```
import React, { Component } from "react";

class Counter extends Component {
  state = { counter: 0 };

  ...
}
```

**Comment by christianalfoni** [comment]
Yeah, would be great, but this is not official JavaScript syntax yet, so it is not part of CodeMirror linter. Have to create issue on CodeMirror to get this in :-/
