### ISSUE TITLE
Support for jsx

### ISSUE THREAD

**Issue by ekulabuhov** [cerebral/webpackbin#5]
Currently I get an error when trying to add jsx file or trying to load an npm package that contains jsx file. I guess jsx should be treated the same way as js files.

EDIT: scrap the npm package problem. Seems like one particular package that is causing problem. Most of them should be precompiled. 

I do have a fix for user created JSX. Should I create a PR?

**Comment by christianalfoni** [comment]
Yeah, please do. I though `.jsx` was ancient though... I though babel made jsx/es2015 transpiling just normal transpiling :) It is all javascript at the end :)

But yeah, would love to see what you have come up with!

**Comment by Guria** [comment]
Yeah, there is a lot of recommendations to use just `.js` extension. On the other hand I can't see any drawbacks to support it.

**Comment by ekulabuhov** [comment]
Definitely not a high priority addition. More of a great excuse for me to lurk through the code and see how things are setup 😄

**Comment by christianalfoni** [comment]
Merged it in, very happy to have someone lurking around :) Will deploy tomorrow after some additional fixes

**Comment by ekulabuhov** [comment]
Thanks! Happy to help out a bit :) Closing this.
