### ISSUE TITLE
Webpackbin site is down / domain registration

### ISSUE THREAD

**Issue by abstractmachines** [cerebral/webpackbin#55]
![screen shot 2018-02-23 at 11 01 08 am](https://user-images.githubusercontent.com/789892/36611612-ef4fc9f8-1888-11e8-9c6a-2e223b230946.png)

**Comment by bebraw** [comment]
See https://twitter.com/christianalfoni/status/967299158867632128 .

> The domain of http://webpackbin.com  has expired, sorry about that, but was too much money to pay for keeping it up for another week. If you need your bin code, you can go to: https://webpackbin-prod.firebaseapp.com/  for now. Move it to http://codesandbox.io  :-)

**Comment by abstractmachines** [comment]
Thank you for all of your hard work Christian! Closing issue.
