### ISSUE TITLE
Class properties not working

### ISSUE THREAD

**Issue by k15a** [cerebral/webpackbin#8]
When I turn the class properties option on and the linter off I still get the error "Code is not valid, check lint messages" when saving the code.

**Comment by christianalfoni** [comment]
Hm, thanks for checking, noted!

**Comment by christianalfoni** [comment]
Hm, I am not able to reproduce this @k15a . Deploying a new version now with a bunch of fixes, but yeah... maybe you could check again. But need step by step what you did :)

**Comment by k15a** [comment]
I just checked if I can still reproduce it. It only happens if you have linting errors while you turn off the linter.

1. Open webpackbin.com
2. Add a div with the id "app"
3. Create a new JS file as entry point
4. Paste the JS code
5. Add `react` and `react-dom` as deps
6. Enable `babel-loader` with ES2015, Class properties and React options
7. There should be a linting error on line 5
8. Turn off the linter
9. Save the files

```JS
import React from 'react'
import { render } from 'react-dom'

class App extends React.Component {
  render = () => {return <div>Hello World</div>}
}

render(<App />, document.getElementById('app'))
```

Hope this helps you :)

**Comment by christianalfoni** [comment]
Thanks for a great description @k15a, deploying fix now :-)
